title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
title: "My Data Science Portfolio"
description: "Projects in ML, NLP, and Time Series"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
